### ISSUE TITLE
Use table driven tests

### ISSUE THREAD

**Issue by easyCZ** [VasilyShelkov/go-advent-of-code-2019#1]
https://github.com/golang/go/wiki/TableDrivenTests ;)

**Comment by VasilyShelkov** [comment]
look who's back from the dead :D sounds like a good idea... finding the golang developer docs/tutorials to be pretty lacking compared to the web community. If you have any other recommendations, I'm all 👂

**Comment by easyCZ** [comment]
https://github.com/easyCZ/advent-of-code-2019 see for some examples
